package de.othr.sw.DreamSchufa.enums;

public enum Art {
    ZAHLUNGSEINGANG,
    NEUESEINKOMMEN,
    ZAHLUNGERFOLGREICH,
    ZAHLUNGABGELEHNT,
    BESCHAEFTIGUNGWECHSEL,
    KREDITAUFGENOMMEN,
    KREDITABBEZAHLT;
}
